### ISSUE TITLE
npm package still at 3.2.0

### ISSUE THREAD

**Issue by ryanoolala** [GovTechSG/singpass-myinfo-oidc-helper#14]
Can we please update the npm repository with the updated releases?

https://www.npmjs.com/package/@govtechsg/singpass-myinfo-oidc-helper

Will like to have the new package.json changes without the dependency vulnerabilities in 3.2.0 thank you.

**Comment by dyihoon90** [comment]
agreed, let's try and fix the pipeline soon so that the team can publish to npm

**Comment by ryanoolala** [comment]
Hi guys, any updates on this?

**Comment by dyihoon90** [comment]
thanks, have published to npm registry 4.2.25.
