### ISSUE TITLE
myinfo/domain/map.ts - fill gaps from NDI MyInfo Code Listing

### ISSUE THREAD

**Issue by LoneRifle** [GovTechSG/singpass-myinfo-oidc-helper#2]
Hi, LoneRifle from @opengovsg ([Open Government Products](https://open.gov.sg)) here. Filing an issue after discussing with @dyihoon90 some time ago just so we remember to do something about it.

`myinfo/domain/map.ts` contains a data dictionary that maps an enumerated index to a corresponding human-readable descsription, to supplement what was generated in `myinfo-domain.ts`, providing enumerated values for fields where we expect them but don't get them after running dtsgenerator. It has yet to provide complete coverage of all known MyInfo code fields, eg SchoolCode is notably absent.

Gaps can be filled using the code listing spreadsheet (.xlsx) [dead link] found at NDI. Alternatively, transform the data dictionary found at [opengovsg/myinfo-gov-client](https://github.com/opengovsg/myinfo-gov-client/blob/master/src/myinfo-data.js)

**Comment by dyihoon90** [comment]
Hey there @LoneRifle we totally missed the code listing spreadsheet on the NDI page. I just went to dig around the NDI website and found it tucked away at https://www.ndi-api.gov.sg/assets/lib/trusted-data/myinfo/downloads/myinfo-api-code-tables.xlsx

I think using NDI team's code listing as the source of truth will definitely make it easier to maintain the repo. Potentially can write a script to parse the xlsx and generate the a versioned map.ts on every build.

I not working on related features now so not sure about the use cases for this map, would be great to get inputs from you guys. Thanks!

**Comment by LoneRifle** [comment]
Thanks for replying. The FormSG team will likely get to this issue first, since we need to have the full data dictionary and would rather reuse this package to get to v3 rather than maintain our own.

**Comment by LoneRifle** [comment]
Looping in @ndi-trusted-data in case they want to comment

**Comment by LoneRifle** [comment]
It seems that the code tables was removed by @ndi-trusted-data
